/**
 * `dist/web` を gzip して `webdist/` へ置く。Go の `//go:embed` で取り込むため。
 *
 * gzip のまま埋めて gzip のまま返すので、バイナリサイズも転送量も小さくなる。
 * 12.1MB のうち 10.3MB は shiki の言語チャンクで、gzip すると全体で 2.4MB まで落ちる。
 */
import { mkdir, readdir, readFile, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const WEB_DIR = join(ROOT, "dist", "web");
const OUT_DIR = join(ROOT, "webdist");

async function walk(dir) {
  const entries = await readdir(dir, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) return walk(full);
      return entry.isFile() ? [full] : [];
    }),
  );
  return nested.flat();
}

try {
  await stat(WEB_DIR);
} catch {
  console.error(`[pack-web] ${WEB_DIR} がありません。先に vite build を実行してください。`);
  process.exit(1);
}

await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });

// go:embed は 1 つもファイルが無いとコンパイルエラーになるので、必ず残す番人を置く
await writeFile(join(OUT_DIR, "keep"), "generated by scripts/pack-web.mjs\n");

const files = (await walk(WEB_DIR)).toSorted();

const results = await Promise.all(
  files.map(async (file) => {
    const body = await readFile(file);
    const gz = gzipSync(body, { level: 9 });
    const rel = relative(WEB_DIR, file).split(sep).join("/");
    const target = join(OUT_DIR, `${rel}.gz`);

    await mkdir(dirname(target), { recursive: true });
    await writeFile(target, gz);

    return { raw: body.length, packed: gz.length };
  }),
);

const raw = results.reduce((sum, r) => sum + r.raw, 0);
const packed = results.reduce((sum, r) => sum + r.packed, 0);

const mb = (n) => `${(n / 1024 / 1024).toFixed(1)}MB`;
console.log(`[pack-web] ${files.length} files: ${mb(raw)} → ${mb(packed)} (gzip)`);
